name: Elca Theme
description: A clean Jekyll theme
baseurl: ""
url: ""
markdown: kramdown

# Theme settings
title: Elca
description: The Ultimate Doc
author: Izumie

# Build settings
theme: elca
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
