# Site title and description
title: "Your Site Title"
title_short: "YST" # Short version for header
description: "Your site description"
keywords: "your,keywords,here"
author: "Your Name"

# Logo (optional)
logo: "https://mr-izu.github.io/logos/qxel/transparent_logo.png" # Path to your logo

# Navigation configuration
navigation:
  - title: "Home"
    url: "/"
  
  - title: "Community"
    url: "/community/"
    dropdown:
      - title: "About Us"
        url: "/about/"
      - title: "Join Community"
        url: "/join/"
      - title: "Features & Products"
        url: "/features/"
      - title: "Community Survey"
        url: "/survey/"
  
  - title: "What We Support"
    url: "/support/"
  
  - title: "Terms"
    url: "/terms/"
  
  - title: "Privacy"
    url: "/privacy/"
  
  - title: "Report"
    url: "/report/"
